export const subjects = [
    { content: 'Actor' },
    { content: 'Alien Abductee' },
    { content: 'Alien' },
    { content: 'Amputee' },
    { content: 'Astronaut' },
    { content: 'Amputee' },
    { content: 'Astronaut' },
    { content: 'Artist' },
    { content: 'Babysitter' },
    { content: 'Bartender' },
    { content: 'Bank Robber' },
    { content: 'Biker' },
    { content: 'Beach Bum' },
    { content: 'Billionaire' },
    { content: 'Beggar' },
    { content: 'Blind Date' },
    { content: 'Big Foot' },
    { content: 'Bouncer' },
    { content: 'Bridesmaid' },
    { content: 'Camp Counselor' },
    { content: 'Bull Fighter' },
    { content: 'Camper' },
    { content: 'Bungee Jumper' },
    { content: 'Caveman' },
    { content: 'Castaway' },
    { content: 'Cheerleader' },
    { content: 'Chef' },
    { content: 'Class Clown' },
    { content: 'Coach' },
    { content: 'Clown' },
    { content: 'Coal Miner' },
    { content: 'Clown' },
    { content: 'Cowboy' },
    { content: 'Comedian' },
    { content: 'Cupid' },
    { content: 'Couch Potato' },
    { content: 'Dad' },
    { content: 'Dictator' },
    { content: 'Dare Devil' },
    { content: 'Drill Sergeant' },
    { content: 'Diva' },
    { content: 'Dumpster Diver' },
    { content: 'Doctor' },
    { content: 'Executioner' },
    { content: 'Dog' },
    { content: 'Fire Fighter' },
    { content: 'Dog' },
    { content: 'Fire Fighter' },
    { content: 'Fashion Model' },
    { content: 'Fortune Teller' },
    { content: 'Fisherman' },
    { content: 'Fortune Teller' },
    { content: 'Geek' },
    { content: 'Frat Boy' },
    { content: 'Gladiator' },
    { content: 'Gambler' },
    { content: 'Grandma' },
    { content: 'Gangster' },
    { content: 'High School Dropout' },
    { content: 'Ghost' },
    { content: 'Hippie' },
    { content: 'Girl Scout' },
    { content: 'Hitch Hiker' },
    { content: 'Grave Robber' },
    { content: 'Hobo' },
    { content: 'Haunted House Actor' },
    { content: 'Immigrant' },
    { content: 'High School Student' },
    { content: 'Insomniac' },
    { content: 'Hostage' },
    { content: 'Kindergartener' },
    { content: 'Hunter' },
    { content: 'Life Guard' },
    { content: 'Janitor' },
    { content: 'Life Guard' },
    { content: 'Last Person On Earth' },
    { content: 'Lovers' },
    { content: 'Lawyer' },
    { content: 'Lumberjack' },
    { content: 'Little Red Ridinghood' },
    { content: 'Masseuse' },
    { content: 'Lottery Winner' },
    { content: 'Missionary' },
    { content: 'Mad Scientist' },
    { content: 'Mob Boss' },
    { content: 'Magician' },
    { content: 'Nanny' },
    { content: 'Monk' },
    { content: 'Navy Seal' },
    { content: 'Mortician' },
    { content: 'Newlywed' },
    { content: 'Ninja' },
    { content: 'Paper Boy' },
    { content: 'Nurse' },
    { content: 'Pharaoh' },
    { content: 'Olympic Athlete' },
    { content: 'Pirate' },
    { content: 'Paparazzi' },
    { content: 'Pizza Deliverer' },
    { content: 'Party Animal' },
    { content: 'Police Officer' },
    { content: 'Party Host' },
    { content: 'Police Officer' },
    { content: 'Pop Singer' },
    { content: 'Politician' },
    { content: 'Prisoner of War' },
    { content: 'Pregnant Woman' },
    { content: 'Prison Guard' },
    { content: 'Priest' },
    { content: 'Pro Wrestler' },
    { content: 'Princess' },
    { content: 'Quarterback' },
    { content: 'Prom Date' },
    { content: 'Rioter' },
    { content: 'Protester' },
    { content: 'Robot' },
    { content: 'Queen' },
    { content: 'Rock star' },
    { content: 'Rapper' },
    { content: 'Roommate' },
    { content: 'Referee' },
    { content: 'School Bus Driver' },
    { content: 'Rock Climber' },
    { content: 'Soldier' },
    { content: 'Runaway' },
    { content: 'Space Colonist' },
    { content: 'Santa' },
    { content: 'Sports Fan' },
    { content: 'Secret Admirer' },
    { content: 'Sports Mascot' },
    { content: 'Senior Citizen' },
    { content: 'Spy' },
    { content: 'Snowman' },
    { content: 'Substitute Teacher' },
    { content: 'Sorority Girl' },
    { content: 'Tailgater' },
    { content: 'Stewardess' },
    { content: 'Tarzan' },
    { content: 'Super Hero' },
    { content: 'Taxi Driver' },
    { content: 'Surfer' },
    { content: 'Teenager' },
    { content: 'Teacher' },
    { content: 'Tourist' },
    { content: 'The President' },
    { content: 'Vampire' },
    { content: 'Therapist' },
    { content: 'Villain' },
    { content: 'Toddler' },
    { content: 'Waitress' },
    { content: 'Treasure Hunter' },
    { content: 'Witch' },
    { content: 'Tree Hugger' },
    { content: 'Wizard' },
    { content: 'Trucker' },
    { content: 'Zombie' },
]